name: Build and Release TheLegendOfTheGhost

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            executable: TheLegendOfTheGhost_Linux
            extension: tar.gz
          - os: windows-latest
            executable: TheLegendOfTheGhost_Windows.exe
            extension: zip
          - os: macos-latest
            executable: TheLegendOfTheGhost_Mac
            extension: tar.gz
    steps:
    - uses: actions/checkout@v2

    - name: Compile C++ code
      run: g++ -o ${{ matrix.executable }} main.cpp
      shell: bash

    - name: Archive the build (Linux and macOS)
      if: matrix.os != 'windows-latest'
      run: tar -czvf ${{ matrix.executable }}.${{ matrix.extension }} ${{ matrix.executable }}

    - name: Archive the build (Windows)
      if: matrix.os == 'windows-latest'
      run: Compress-Archive -Path ${{ matrix.executable }} -DestinationPath ${{ matrix.executable }}.${{ matrix.extension }}
      shell: pwsh

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.executable }}.${{ matrix.extension }}
        path: ${{ matrix.executable }}.${{ matrix.extension }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download all Artifacts
      uses: actions/download-artifact@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TheLegendOfTheGhost_Linux.tar.gz
        asset_name: TheLegendOfTheGhost_Linux.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TheLegendOfTheGhost_Windows.exe.zip
        asset_name: TheLegendOfTheGhost_Windows.exe.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (Mac)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TheLegendOfTheGhost_Mac.tar.gz
        asset_name: TheLegendOfTheGhost_Mac.tar.gz
        asset_content_type: application/gzip
